spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/appointment_applet?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useOldAliasMetadataBehavior=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: 2587
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
