spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sms_group?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useOldAliasMetadataBehavior=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#  redis:
#    host: localhost
#    port: 6379
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true